### ISSUE TITLE
ARM emulation broken with new docker server

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#19]
Image is broken on Mac with new docker server versions (17.03.1-ce and 17.05.0-ce-rc1-mac8 (16582)).
The same image worked in emulation on Mac till version 1.13.1

Error message is:
```
agile-ui         | runtime stack:
agile-ui         | runtime.throw(0x6396b5, 0x9)
agile-ui         | 	/usr/local/go/src/runtime/panic.go:566 +0x78
agile-ui         | runtime.newosproc(0x10b1e000, 0x10b2dfe0)
agile-ui         | 	/usr/local/go/src/runtime/os_linux.go:160 +0x1b0
agile-ui         | runtime.newm(0x69ee24, 0x0)
agile-ui         | 	/usr/local/go/src/runtime/proc.go:1572 +0x12c
agile-ui         | runtime.main.func1()
agile-ui         | 	/usr/local/go/src/runtime/proc.go:126 +0x24
agile-ui         | runtime.systemstack(0x8a6000)
agile-ui         | 	/usr/local/go/src/runtime/asm_arm.s:247 +0x80
agile-ui         | runtime.mstart()
agile-ui         | 	/usr/local/go/src/runtime/proc.go:1079
agile-ui         | 
agile-ui         | goroutine 1 [running]:
agile-ui         | runtime.systemstack_switch()
agile-ui         | 	/usr/local/go/src/runtime/asm_arm.s:192 +0x4 fp=0x10b187ac sp=0x10b187a8
agile-ui         | runtime.main()
agile-ui         | 	/usr/local/go/src/runtime/proc.go:127 +0x5c fp=0x10b187d4 sp=0x10b187ac
agile-ui         | runtime.goexit()
agile-ui         | 	/usr/local/go/src/runtime/asm_arm.s:998 +0x4 fp=0x10b187d4 sp=0x10b187d4
agile-ui         | starting version 3.2.1
agile-ui         | runtime: failed to create new OS thread (have 2 already; errno=22)
agile-ui         | fatal error: newosproc
```
and then it restarts.

**Comment by cskiraly** [comment]
This is just emulation of the armv7 image on x86_64 over Mac, thus it is not so critical. Still, other images work on the new docker version, while this does not.

**Comment by craigmulligan** [comment]
interesting. This is with v0.2.0 right. Did you test `v0.2.0` on an older version of docker for mac? i remember testing it but I'm not sure what docker v I was on..

**Comment by craigmulligan** [comment]
Is this still and issue @cskiraly?

**Comment by cskiraly** [comment]
to be verified. Since than I have moved away from emulation, making sure native images are available for each component. We can close for now and reopen if needed ....

**Comment by craigmulligan** [comment]
Sounds good.
